=== chsxf/CiderKit-DTDs-Schemas/ckuiml.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ckuiml">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="element" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="element">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="style" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="data" minOccurs="0" maxOccurs="unbounded" />
                <xs:element ref="element" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="type" type="xs:string" use="optional" default="container" />
            <xs:attribute name="id" type="xs:ID" use="optional" />
            <xs:attribute name="class" type="xs:string" use="optional" />
        </xs:complexType>
    </xs:element>

    <xs:element name="data">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="value" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

    <xs:element name="style">
        <xs:complexType>
            <xs:attribute name="name" type="xs:string" use="required" />
            <xs:attribute name="value" type="xs:string" use="required" />
        </xs:complexType>
    </xs:element>

</xs:schema>

=== chsxf/CiderKit-DTDs-Schemas/ckuiml-sample.xml
<?xml version="1.0" encoding="UTF-8" ?>
<ckuiml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://dtdschema.ciderkit.chsxf.dev/ckuiml.xsd">
    <element>
        <style name="anchored-position" value="10px 10px" />
        <style name="anchors" value="left bottom" />
        <style name="transform-origin" value="left bottom" />

        <element type="button" id="quit-button">
            <style name="anchors" value="left bottom" />
            <style name="anchored-position" value="0 0" />
            <style name="transform-origin" value="left bottom" />
            <style name="padding" value="3px 5px" />

            <data name="text" value="Quit Game" />
        </element>

        <element type="button" id="settings-button">
            <style name="anchors" value="left bottom" />
            <style name="anchored-position" value="0 25px" />
            <style name="transform-origin" value="left bottom" />
            <style name="padding" value="3px 5px" />

            <data name="text" value="Settings" />
            <data name="disabled" value="true" />
        </element>
        
        <element type="button" id="play-button">
            <style name="anchors" value="left bottom" />
            <style name="anchored-position" value="0 50px" />
            <style name="transform-origin" value="left bottom" />
            <style name="padding" value="3px 5px" />

            <data name="text" value="Play" />
        </element>
    </element>
</ckuiml>
